version: 1.2
workflows:
  - name: multi_cnv_validation
    subclass: WDL
    primaryDescriptorPath: /CNV/somatic/crsp_and_wgs/wdl/multi_cnv_validation.wdl
  - name: cnv_validation
    subclass: WDL
    primaryDescriptorPath: /CNV/somatic/crsp_and_wgs/wdl/cnv_validation.wdl
  - name: purity_cnv_validation
    subclass: WDL
    primaryDescriptorPath: /CNV/somatic/crsp_and_wgs/wdl/purity_cnv_validation.wdl