name: gcnv-eval
channels:
- defaults
dependencies:
- pip=9.0.1=py36_1
- python=3.6.2=0
- setuptools=36.4.0=py36_1
- zlib=1.2.11=0
- pip:
  - biopython==1.70
  - matplotlib==2.1.0
  - numpy==1.13.3
  - pandas==0.21.0
  - pyvcf==0.6.8
